###
GET http://localhost:4000/api/employees

###
POST  http://localhost:4000/api/employees
Content-Type: application/json

{
    "name":"paul",
    "position":"software developer",
    "office":"ecuador",
    "salary":2000
}

###
GET http://localhost:4000/api/employees/5fb9a5088ce7442d9387a41b


